services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 15s ; python3 ./stream.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306' 

  grafana:
      image: grafana/grafana:8.2.0
      ports:
        - "3000:3000"
      volumes: 
        - ./provisioning:/etc/grafana/provisioning
      depends_on:
        - mysql