version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - ./tabla:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
      # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: stream
    ports:
      - 3306:3306

  adminer:
    image: adminer
      # restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    volumes: 
      - ./provisioning:/etc/grafana/provisioning

        #  stream:
        # image: stream-python:v1

